version: 2.1


jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - java/install
      - run: chmod +x mvnw
      - run: ./mvnw clean install -DskipTests=false

workflows:
  build:
    jobs:
      - build
